export const LANGUAGES = [
  { code: "af", name: "Afrikaans", native: "Afrikaans" },
  { code: "ar", name: "Arabic", native: "العربية" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "cs", name: "Czech", native: "Čeština" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "en", name: "English", native: "English" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "et", name: "Estonian", native: "Eesti" },
  { code: "fa", name: "Persian", native: "فارسی" },
  { code: "fi", name: "Finnish", native: "Suomi" },
  { code: "fr", name: "French", native: "Français" },
  { code: "gl", name: "Galician", native: "Galego" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "he", name: "Hebrew", native: "עברית" },
  { code: "hi", name: "Hindi", native: "हिंदी" },
  { code: "hr", name: "Croatian", native: "Hrvatski" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia" },
  { code: "it", name: "Italian", native: "Italiano" },
  { code: "ja", name: "Japanese", native: "日本語" },
  { code: "ka", name: "Georgian", native: "ქართული" },
  { code: "kk", name: "Kazakh", native: "Қазақ" },
  { code: "km", name: "Khmer", native: "ភាសាខ្មែរ" },
  { code: "ko", name: "Korean", native: "한국어" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių" },
  { code: "lv", name: "Latvian", native: "Latviešu" },
  { code: "mk", name: "Macedonian", native: "Македонски" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "mn", name: "Mongolian", native: "Монгол" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "my", name: "Burmese", native: "မြန်မာ" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "nl", name: "Dutch", native: "Nederlands" },
  { code: "pl", name: "Polish", native: "Polski" },
  { code: "ps", name: "Pashto", native: "پښتو" },
  { code: "pt", name: "Portuguese", native: "Português" },
  { code: "ro", name: "Romanian", native: "Română" },
  { code: "ru", name: "Russian", native: "Русский" },
  { code: "si", name: "Sinhala", native: "සිංහල" },
  { code: "sl", name: "Slovene", native: "Slovenščina" },
  { code: "sv", name: "Swedish", native: "Svenska" },
  { code: "sw", name: "Swahili", native: "Kiswahili" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "th", name: "Thai", native: "ไทย" },
  { code: "tl", name: "Tagalog", native: "Tagalog" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
  { code: "uk", name: "Ukrainian", native: "Українська" },
  { code: "ur", name: "Urdu", native: "اردو" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "xh", name: "Xhosa", native: "isiXhosa" },
  { code: "zh", name: "Chinese", native: "中文" },
] as const;

export type LanguageCode = typeof LANGUAGES[number]['code'];

export const getLanguageByCode = (code: string) => {
  return LANGUAGES.find(lang => lang.code === code);
};
